- name: Deploy via SFTP
uses: appleboy/scp-action@master
with:
  host: ${{ secrets.FTP_HOST }}
  username: ${{ secrets.FTP_USERNAME }}
  password: ${{ secrets.FTP_PASSWORD }}
  port: 22
  source: "./*"
  target: "/public_html"
